### PR TITLE
Add support for setting Cache-Control headers

### LINKED ISSUE #36: Can't set Cache-Control header
As far as I can tell there is no way to set a `Cache-Control` header from the `MulterS3` parameters. I really really don't wanna make a separate request to S3 just to update this setting 😆 

Should be pretty easy to bake this into `MulterS3`, would you accept a PR for this?

I'm thinking an optional parameter, something like this:

```javascript
var upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: 'some-bucket',
    cacheControl: 'max-age=31536000',
    acl: 'public-read',
    key: function (req, file, cb) {
      cb(null, Date.now().toString())
    }
  })
});
```

### PR DESCRIPTION
**Pull request by lukechilds**
Fixes #36

### CODE REVIEW

**Comment by LinusU** [comment]
LGTM

**Comment by lukechilds** [comment]
Yeah, sure 👍

**Comment by lukechilds** [comment]
@LinusU done :)

**Comment by LinusU** [comment]
Awesome, thanks for your contribution

LGTM

**Comment by badunk** [comment]
looks good, but I'm honestly not very happy w/ the entire chain of callbacks we're tacking onto it - that's outside of this PR

**Comment by LinusU** [comment]
@badunk I'll submit a pull request to fix that as soon as this is merged, sounds good?

**Comment by badunk** [comment]
oh yeah for sure, thanks @LinusU

**Comment by lukechilds** [comment]
Yeah I agree, I threw up in my mouth a little when I saw that, I was just following the convention 😆 

It could still be trimmed down quite a bit after your latest PR.

Also, just a suggestion, but instead of manually implementing all the stuff you wanna pass through to S3 (metadata, cache control, acl, content type etc) it might be worth having one `s3Params` property that gets merged with the default S3 param object. That way people can add any options that the S3 lib supports without requiring any extra modifications to this lib.

**Pull request merged**
