### PR TITLE
Added the option to transform files before upload

### PR DESCRIPTION
**Pull request by gmenih341**
Added the option to have a file transformed into multiple files and then uploaded to s3.

Please let me know if this is something other users might find useful, and if anything needs to be fixed before it can be merged.

### CODE REVIEW

**Comment by LinusU** [comment]
Maybe expressjs/multer#399 is a better solution to this, what do you think?

**Comment by gmenih341** [comment]
@LinusU yes, that seems like a better solution! I only created this PR, because I needed it in one of my projects and thought others might need it too.

**Comment by LinusU** [comment]
Would you mind trying out that code, it's published under the next tag (`npm install --save multer@next`)?

I would love some feedback! Good or bad 👍

**Comment by und0ck3d** [comment]
Any news or expectations on this?

**Comment by gmenih341** [comment]
@und0ck3d someone had forked this PR and published to npm under the name `multer-s3-transform`, so feel free to use that while you wait for the release of `multer-next`.

**Comment by und0ck3d** [comment]
@gmenih341 thanks for pointing that! happy coding :smiley:

**Pull request closed without merging**
