### PR TITLE
Feature/aws sdk options

### PR DESCRIPTION
**Pull request by badunk**
@LinusU I took your branch, merged it in with just a small commit for syntax and fixing the `npm test` command.

I also tested that it works locally.  If everything else is good, I'd like to merge that in today

Thanks

### CODE REVIEW

**Comment by LinusU** [comment]
Looking good 👍

**Comment by LinusU** [comment]
@badunk Just saw that you published this as a minor release `1.5.0`, the problem with that is that most people will now be upgraded automatically and their things will break.

I would recommend you to `npm deprecated multer-s3@1.5.0` and then publish the old version (1.4.1) as version `1.6.0`. Then finally publish the latest version as `2.0.0`.

Do you think it sounds good?

**Comment by badunk** [comment]
Actually I think you're right.  If the default is caret in npm then things will break.  I'll go ahead and do that

**Comment by badunk** [comment]
@LinusU should be done thanks for the tip

**Pull request merged**
